# Generated by Django 3.2.4 on 2021-06-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
